name: Test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    strategy:
      matrix:
        go: ["1.18", "1.19", "1.20"]
        os:
          [
            "windows-latest",
            "ubuntu-latest",
            "macos-latest",
          ]
    env:
      OS: ${{ matrix.os }}
      GO: ${{ matrix.go }}
    runs-on: ${{ matrix.os }}
    name: Build & test with Go ${{ matrix.go }} on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v -race -covermode=atomic -coverprofile="coverage.out" -coverpkg=./... ./...

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
          env_vars: OS,GO
          flags: unittests
